table EXTRACTED_TEXT
	lineageTag: d4734a99-3602-42cb-b329-111f37303a19

	column id
		dataType: int64
		formatString: 0
		lineageTag: 3d82a98e-37e7-490b-9039-ee3cf01ba76b
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column extraction_run_id
		dataType: int64
		formatString: 0
		lineageTag: f210c6b8-3f20-469e-bb42-76ea96d349c5
		summarizeBy: none
		sourceColumn: extraction_run_id

		annotation SummarizationSetBy = Automatic

	column raw_text
		dataType: string
		lineageTag: f51c4585-18f4-443b-9951-8515d21d7184
		summarizeBy: none
		sourceColumn: raw_text

		annotation SummarizationSetBy = Automatic

	partition EXTRACTED_TEXT = m
		mode: import
		source =
				let
				    Zdroj = Python.Execute("import sqlite3#(lf)#(lf)import pandas as pd#(lf)#(lf)#(lf)conn = sqlite3.connect(r'D:\PIS\powerbi\projects\bonus\database.db')#(lf)#(lf)#(lf)EXTRACTED_TEXT_EVAL = pd.read_sql_query(""SELECT * FROM EXTRACTED_TEXT_EVAL"", conn)#(lf)#(lf)ANALYZED_TEXT_EVAL = pd.read_sql_query(""SELECT * FROM ANALYZED_TEXT_EVAL"", conn)#(lf)#(lf)DOCUMENT = pd.read_sql_query(""SELECT * FROM DOCUMENT"", conn)#(lf)#(lf)MODEL = pd.read_sql_query(""SELECT * FROM MODEL"", conn)#(lf)#(lf)PROMPT = pd.read_sql_query(""SELECT * FROM PROMPT"", conn)#(lf)#(lf)EXTRACTION_RUN = pd.read_sql_query(""SELECT * FROM EXTRACTION_RUN"", conn)#(lf)#(lf)EXTRACTED_TEXT = pd.read_sql_query(""SELECT * FROM EXTRACTED_TEXT"", conn)#(lf)#(lf)ANALYZED_TEXT = pd.read_sql_query(""SELECT * FROM ANALYZED_TEXT"", conn)#(lf)#(lf)#(lf)#(lf)conn.close()"),
				    EXTRACTED_TEXT1 = Zdroj{[Name="EXTRACTED_TEXT"]}[Value],
				    #"Změněný typ" = Table.TransformColumnTypes(EXTRACTED_TEXT1,{{"id", Int64.Type}, {"extraction_run_id", Int64.Type}, {"raw_text", type text}})
				in
				    #"Změněný typ"

	annotation PBI_NavigationStepName = Navigace

	annotation PBI_ResultType = Table

